from pathlib import Path
import report_io
import json,subprocess
R=Path(__file__).resolve().parents[3];E=R/'docs/検証/本編実装/d04b-ui-02/reproduction-20261005';O='72d0eb58c7e3d04759f1ab56a939d1dff20a46b2'
def code(path,locator):return {'commit':O,'path':path,'blob':subprocess.check_output(['git','rev-parse',O+':'+path],cwd=R,text=True).strip(),'locator':locator}
base='docs/検証/UI/readability/co-u02/'
rows=[
 {'id':'DEC-UI-01','difference_ids':['V-E05','V-P01','V-P07','V-P08','V-P10','V-P11','V-P12','V-P14','V-P15'],'owner':'UI改善','reason':'基準は既存SVGを要求するが固定原本vendorの30件subsetにMountain/Store/LayoutGrid/Check/Clock3/Inbox/Plus/Undo2等が登録されず、実画像では未描画かfallback。Godotは基準の既存SVGを使った。原本不備を無断で承認済み差異へしない。','expected_decision':'固定基準どおりのSVGを正とするか、現固定bundleの未登録／fallbackを正とするか、各記号の参照版をUIが明示する。新しい素材制作は不要。','sources':[code(base+'vendor/build-icons.cjs','names / generated subset'),code(base+'acquisition-preview/layout.js','icon / lane / card / cp-clock / purchaseTrack'),code(base+'exploration.js','actorIcon / symbol mountain')],'evidence':['source-representative-final/manifest.json','source-remaining-final/manifest.json','id-comparisons.json'],'resumption':'UI指定の同じ既存定義とlocatorへ該当IDだけ合わせ、関連原寸対を再提出。'},
 {'id':'DEC-UI-02','difference_ids':['V-P07'],'owner':'UI改善（UI adapter）、公開名を変える契約判断が必要ならゲームバランス検討','reason':'取得メタは原本layoutがit.attributeを読む一方、公開札詳細はattrを持ち、原本の該当実画像では属性文字が空。Godotは既存公開attrを表示している。','expected_decision':'既存公開attr→原本attributeの表示対応を正とするか、現在の空表示が了承対象かを固定する。規則や札属性を変えない。','sources':[code(base+'acquisition-preview/runtime.js','publicFixture catalogue={key,...clone(detail)}'),code(base+'acquisition-preview/layout.js','card it.attribute')],'evidence':['source-representative-final/light-repro-home-card.nodes.json','preparation-light-final/repro-home-card.nodes.json'],'resumption':'固定された表示対応へ同じ札面だけ修正し、取得/編成/詳細とDTO不変を確認。'},
 {'id':'DEC-UI-03','difference_ids':['V-W02','V-W04'],'state_ids':['ST-E09'],'owner':'UI改善','reason':'原本#cw-useは180msでtransient予測を開く。root内の空白離脱はpointeroverがleaveTimerを無条件取消するため閉じず、root外離脱で160ms閉鎖。Godotは窓外の空白で160ms閉鎖。基準文言と現行実挙動が食い違う。','expected_decision':'160ms窓外離脱基準を正とするか、現固定原本のroot内保持を継承するかを明示。既存Godotの予測hover追加入口の採否も独立判断。','sources':[code(base+'exploration.js','pointerover / pointerout / preview(false)')],'evidence':['source-required-boundaries-complete/manifest.json','source-required-boundaries-complete/light-repro-hover-sequence.json','hover-use-light/repro-hover-sequence.json','hover-use-dark/repro-hover-sequence.json','related-final/inheritance.json'],'resumption':'決定した一つの挙動へ共通hoverだけ合わせ、同じ合法fixtureのenter/内側leave/root外leave/pin/クリックと非実行を限定再確認。'},
 {'id':'DEC-UI-04','difference_ids':['V-C01'],'owner':'UI改善','reason':'書体faceの誤解決、行高、末行、位置は修正。過去のOS/AAが未記録で、現固定原寸対のAA/丸め残差を自動許容しない。','expected_decision':'現固定原本の解決書体と等倍領域を基準に、残る具体領域の適合条件を固定。Godot標準/試作/仕上げを免除根拠にしない。','sources':[code(base+'prose-layout.js','measured layout')],'evidence':['source-font-leaves/manifest.json','environment/os-collection-faces.json','id-comparisons.json','preparation-light-final/repro-home.json'],'resumption':'判定された文字領域のmetrics/line placement/AA方法を同じ本編で修正し、読む順と原寸対を追補。'},
 {'id':'DEC-UI-05','difference_ids':['V-W01','V-W10','V-H04','V-H05','V-P15'],'state_ids':['ST-P08'],'owner':'UI改善。規則・共通契約の意味を変える場合だけゲームバランス検討','reason':'前版の本文詳細/任意本文の読了して閉じる、未公開予測補足、Windows保存・診断・復旧に原本の一対一の窓/footerがない。固定原本のCW-M1-public-0.6ではowned入口をcollectionへ送るが、そのA06部品にロック/解除/変換見積の入口がなく、ST-P08の同状態窓は未取得。Godotの既確認ロック/見積/変換・保存機能を保全している。','expected_decision':'各追加導線と補足、A06での既存ロック/解除/見積/変換失敗を、どの共通窓/行/footerへ置くか具体の原本対応を固定。保存や読了処理を削除して一致を作らない。','sources':[code(base+'journey/view.js','unifiedAcquisition action routing / connectedAcquisition'),code(base+'journey/panels.js','menu items / !unifiedAcquisition owned / conversion panel'),code(base+'acquisition-preview/layout.js','localAction / renderDialog')],'evidence':['comparisons.json','source-extra-final/manifest.json','related-final/interaction.json','fixed-light-second/legal-acquisition.json','related-final/failure.json','related-final/corrupt.json'],'resumption':'固定対応へ表示だけ移し、本文読了/ロック/見積/変換/保存拒否/復旧と関連使用先を限定確認。'},
 {'id':'DEC-UI-06','difference_ids':['V-W07'],'state_ids':['ST-W05'],'owner':'UI改善','reason':'同じ合法踏破済み保存の自然overflowで、原本は親を597px送った後、札詳細と戻るで0pxへ戻る。本編は実親scrollを保持した。採取補助の最初のNode再参照誤りも保全し、最終記録は生きた実ControlとDTO/byte不変を確認。未取得の全scroll量という曖昧な残件へ置かず、実際の基準/原本の食い違いへ限定。','expected_decision':'親scroll保持の基準を正とするか、現原本の先頭復帰を継承するかを固定する。公開記録・保存の値は変更不要。','sources':[code(base+'journey/view.js','scrollMemory / scrollKey / render / record-detail / record-back'),code(base+'journey/records.js','recordsPanelView target parent')],'evidence':['source-required-states-final/manifest.json','memory-light-final/repro-record-memory.json','memory-dark-final/repro-record-memory.json','comparisons.json'],'resumption':'決定された一つの挙動へ記録の表示だけ合わせ、同じ自然overflow/親子/戻るを再採取する。'}]
I='572bb9a59b914345830df5c18f910a1deb6af2bc'
rows[-1]['evidence']=['source-required-states-neutral/manifest.json','common-light-followup/repro-record-memory.json','common-dark-complete/repro-record-memory.json','comparisons.json']
(E/'原本判断への返却.json').write_text(json.dumps({'implementation_sha':I,'status':'依頼内未解消','items':rows,'other_work_messages_sent':False,'not_an_exception':True},ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print('specific UI decisions',len(rows))
