// Generated by scripts/generate-m1-content.py; input 0.1 trial values.
const data = {
  "schema": "CW-M1-input-1",
  "version": "0.1",
  "rule_set_id": "CW-M1-rules-0.1",
  "content_set_id": "CW-M1-SCN001-0.1",
  "card_registry_id": "CW-M1-cards-0.1",
  "initial": {
    "phase": "home",
    "nextRun": 0,
    "unspent_units": 0,
    "paid_learning_units": 0,
    "materials": {},
    "inventory": {},
    "learned": {},
    "equipped": [],
    "current_offer": null,
    "unlocked": [
      "f",
      "h",
      "l",
      "j",
      "g",
      "r",
      "fast",
      "read",
      "sweep",
      "salve"
    ],
    "free_card_bases": [
      "f",
      "h",
      "l",
      "j",
      "g",
      "r",
      "fast",
      "read",
      "sweep",
      "salve"
    ],
    "deck_counts": {
      "l": 2,
      "fast": 1,
      "f": 2,
      "sweep": 1,
      "h": 2,
      "read": 1,
      "r": 1,
      "salve": 1,
      "g": 1
    },
    "draft": null,
    "casebook": {
      "SCN-001": {
        "attempts": 0,
        "status": "unresolved",
        "first_resolved_event": null,
        "visible_clue_ids": [],
        "read_text_ids": [],
        "first_clue_events": {},
        "first_route_checked_event": null,
        "run_achievements": {}
      }
    }
  },
  "rules": {
    "units_per_point": 100,
    "deck": {
      "size": 12,
      "per_base_cap": 2,
      "owned_uid_max_occurrences": 1,
      "initial_build": "guard3",
      "free_source": "initial.free_card_bases",
      "unlocked_is_free": false,
      "cap_aggregation": "base across all variants, not blueprint or display name",
      "consumable_reset": "finite per expedition; selected copy recreated next departure; no refill fee or permanent inventory consumption"
    },
    "equipment": {
      "policy": "cost",
      "cost_limit": 8,
      "base_cost": {
        "PS01": 2,
        "PS02": 3,
        "PS03": 2,
        "PS04": 2
      },
      "affix_surcharge": {
        "borrowed": 0,
        "focused_B": 0,
        "swift": 0,
        "forceful": 1,
        "sluggish": 0
      },
      "duplicate_base_limit": null,
      "same_uid_max_occurrences": 1,
      "learned_plain_option_count_per_base": 1,
      "extra_copy_requires_owned_uid": true,
      "all_selected_bases_must_be_learned": true,
      "capacity_is_not_spending": true
    },
    "learning": {
      "bases": {
        "PS01": {
          "cost": 2,
          "placement_discount": 2
        },
        "PS02": {
          "cost": 2,
          "hit_bonus": 20
        },
        "PS03": {
          "cost": 2,
          "guard_bonus": 2
        },
        "PS04": {
          "cost": 2,
          "heal_bonus": 4
        }
      },
      "cost_units": {
        "PS01": 200,
        "PS02": 200,
        "PS03": 200,
        "PS04": 200
      },
      "refund": "actual historical paid amount for explicitly cancelled base; exact and free",
      "cancel_unequips_same_base": true,
      "cancel_preserves_inventory": true,
      "implicit_refund": false
    },
    "conversion": {
      "value_bands_units": {
        "ordinary": 200,
        "special": 400
      },
      "rate": [
        1,
        4
      ],
      "rounding": "floor(value_band_units * numerator / denominator) per selected item; add integer units retaining point remainder",
      "ordinary_return_units": 50,
      "special_return_units": 100,
      "materials_eligible": false,
      "require_owned_not_locked_and_unreferenced": true,
      "references": [
        "equipment",
        "confirmed_deck",
        "saved_draft"
      ],
      "historical_learning_refund_uses_conversion_rate": false
    },
    "player": {
      "hp": 40,
      "max_posture": 100,
      "hand_size": 3,
      "return_hp": 40
    },
    "knowledge": {
      "schema": "AD1",
      "disclosure": "first_resolution",
      "grant_results": [
        "defeated",
        "traversed"
      ],
      "no_grant_result": "retired",
      "retention": "observed_immediately",
      "identity": [
        "knowledge_profile_id",
        "catalogue_version"
      ],
      "current_private_deck": "unknown"
    },
    "run_identity": {
      "run": "JSON.stringify(['CW-M1-run-1',campaign_id,nextRun])",
      "index": "nextRun before increment",
      "seed": "nextRun before increment; nonnegative safe integer; no modulo/reuse",
      "increment": "only atomic successful depart",
      "stream_namespace": "crossweave:AH1",
      "stream_key": "{actor}|{initial,allocation,generation,selection,target}",
      "stream_seed": "{namespace}:{seed}:{stream_key}",
      "stream_initializer": "CPython random.Random(string), version=2 MT19937 state, as existing choice_inputs.py; browser-compatible initializer must be implemented/checked in D02, no Python subprocess in browser",
      "resume": "restore all saved RNG states; never regenerate"
    },
    "action_cost": {
      "resolve": "base place_cost/match_cost + sum(card affix cost deltas); then max(1, cost - applicable passive discount) * actor action_cost_scale",
      "derived_card_cost_fields": "store compiled base+affix intervals; do not add cost_delta twice",
      "life": "decrement unused hand after that owner action by 1; field cards have no hand expiry",
      "normal_expiry": "shared recovery unless consume_on_recover or doomed exception",
      "prediction": "current action and current reservations only; never future choices or guaranteed next-turn arrival"
    }
  },
  "cards": {
    "f": {
      "base_id": "f",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "f",
        "name": "牽制",
        "attr": "A",
        "kind": "attack",
        "power": 3,
        "hit": 70,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": 30,
        "life": 2,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"f\",\"name\":\"牽制\",\"attr\":\"A\",\"kind\":\"attack\",\"power\":3,\"hit\":70,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":30,\"life\":2,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "h": {
      "base_id": "h",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "h",
        "name": "重撃",
        "attr": "B",
        "kind": "attack",
        "power": 12,
        "hit": 30,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": -20,
        "life": 3,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"h\",\"name\":\"重撃\",\"attr\":\"B\",\"kind\":\"attack\",\"power\":12,\"hit\":30,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":-20,\"life\":3,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "l": {
      "base_id": "l",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "l",
        "name": "踏み込み",
        "attr": "B",
        "kind": "attack",
        "power": 4,
        "hit": 50,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 6,
        "field_hit": 0,
        "life": 2,
        "place_cost": 8,
        "match_cost": 12,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"l\",\"name\":\"踏み込み\",\"attr\":\"B\",\"kind\":\"attack\",\"power\":4,\"hit\":50,\"evasion\":0,\"crit_gain\":25,\"field_power\":6,\"field_hit\":0,\"life\":2,\"place_cost\":8,\"match_cost\":12,\"consume_on_recover\":null}"
    },
    "j": {
      "base_id": "j",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "j",
        "name": "小突き",
        "attr": "C",
        "kind": "attack",
        "power": 3,
        "hit": 40,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": 0,
        "life": 1,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"j\",\"name\":\"小突き\",\"attr\":\"C\",\"kind\":\"attack\",\"power\":3,\"hit\":40,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":0,\"life\":1,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "g": {
      "base_id": "g",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "g",
        "name": "防御",
        "attr": "D",
        "kind": "guard",
        "power": 3,
        "hit": 0,
        "evasion": 0,
        "crit_gain": 20,
        "field_power": -4,
        "field_hit": 0,
        "life": 2,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "light",
        "sturdy",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"g\",\"name\":\"防御\",\"attr\":\"D\",\"kind\":\"guard\",\"power\":3,\"hit\":0,\"evasion\":0,\"crit_gain\":20,\"field_power\":-4,\"field_hit\":0,\"life\":2,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "r": {
      "base_id": "r",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "r",
        "name": "受け流し",
        "attr": "A",
        "kind": "guard",
        "power": 2,
        "hit": 0,
        "evasion": 0,
        "crit_gain": 40,
        "field_power": -2,
        "field_hit": 0,
        "life": 3,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "light",
        "sturdy",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"r\",\"name\":\"受け流し\",\"attr\":\"A\",\"kind\":\"guard\",\"power\":2,\"hit\":0,\"evasion\":0,\"crit_gain\":40,\"field_power\":-2,\"field_hit\":0,\"life\":3,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "fast": {
      "base_id": "fast",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "fast",
        "name": "速撃",
        "attr": "A",
        "kind": "attack",
        "power": 2,
        "hit": 100,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": -20,
        "life": 1,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"fast\",\"name\":\"速撃\",\"attr\":\"A\",\"kind\":\"attack\",\"power\":2,\"hit\":100,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":-20,\"life\":1,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "sharp": {
      "base_id": "sharp",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "sharp",
        "name": "鋭撃",
        "attr": "A",
        "kind": "attack",
        "power": 8,
        "hit": 40,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": 40,
        "life": 1,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"sharp\",\"name\":\"鋭撃\",\"attr\":\"A\",\"kind\":\"attack\",\"power\":8,\"hit\":40,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":40,\"life\":1,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "brace": {
      "base_id": "brace",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "brace",
        "name": "踏ん張り",
        "attr": "B",
        "kind": "guard",
        "power": 4,
        "hit": 0,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 2,
        "field_hit": 0,
        "life": 1,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "light",
        "sturdy",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"brace\",\"name\":\"踏ん張り\",\"attr\":\"B\",\"kind\":\"guard\",\"power\":4,\"hit\":0,\"evasion\":0,\"crit_gain\":25,\"field_power\":2,\"field_hit\":0,\"life\":1,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "stored": {
      "base_id": "stored",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "stored",
        "name": "溜め打ち",
        "attr": "B",
        "kind": "attack",
        "power": 9,
        "hit": 20,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 4,
        "field_hit": 0,
        "life": 4,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"stored\",\"name\":\"溜め打ち\",\"attr\":\"B\",\"kind\":\"attack\",\"power\":9,\"hit\":20,\"evasion\":0,\"crit_gain\":25,\"field_power\":4,\"field_hit\":0,\"life\":4,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "read": {
      "base_id": "read",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "read",
        "name": "見切り",
        "attr": "C",
        "kind": "guard",
        "power": 1,
        "hit": 0,
        "evasion": 30,
        "crit_gain": 20,
        "field_power": 0,
        "field_hit": 20,
        "life": 3,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "light",
        "sturdy",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"read\",\"name\":\"見切り\",\"attr\":\"C\",\"kind\":\"guard\",\"power\":1,\"hit\":0,\"evasion\":30,\"crit_gain\":20,\"field_power\":0,\"field_hit\":20,\"life\":3,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "sweep": {
      "base_id": "sweep",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "sweep",
        "name": "打ち払い",
        "attr": "D",
        "kind": "attack",
        "power": 4,
        "hit": 60,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": 20,
        "life": 2,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"sweep\",\"name\":\"打ち払い\",\"attr\":\"D\",\"kind\":\"attack\",\"power\":4,\"hit\":60,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":20,\"life\":2,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "salve": {
      "base_id": "salve",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "salve",
        "name": "回復草",
        "attr": "C",
        "kind": "heal",
        "power": 16,
        "hit": 0,
        "evasion": 0,
        "crit_gain": 10,
        "field_power": -4,
        "field_hit": 0,
        "life": 16,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": true
      },
      "affix_allowlist": [
        "light",
        "rich",
        "frail"
      ],
      "free_initial": true,
      "offer_requires_kept_unlock": true,
      "information_signature": "{\"type\":\"salve\",\"name\":\"回復草\",\"attr\":\"C\",\"kind\":\"heal\",\"power\":16,\"hit\":0,\"evasion\":0,\"crit_gain\":10,\"field_power\":-4,\"field_hit\":0,\"life\":16,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":true}"
    },
    "nt_flow": {
      "base_id": "nt_flow",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "nt_flow",
        "name": "返し潮",
        "attr": "A",
        "kind": "attack",
        "power": 3,
        "hit": 70,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 0,
        "field_hit": 30,
        "life": 2,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "content_card_id": "SCN-001-CRD01",
      "source_target_ids": [
        "SCN-001-ACT01",
        "SCN-001-ACT04"
      ],
      "source": "PT-NT scenario.cards/newCard/cost and card_overrides",
      "affix_source": "existing AO1 kind/family constraints; no new affix",
      "information_signature": "{\"type\":\"nt_flow\",\"name\":\"返し潮\",\"attr\":\"A\",\"kind\":\"attack\",\"power\":3,\"hit\":70,\"evasion\":0,\"crit_gain\":25,\"field_power\":0,\"field_hit\":30,\"life\":2,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    },
    "nt_pressure": {
      "base_id": "nt_pressure",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "nt_pressure",
        "name": "潮底の踏み足",
        "attr": "B",
        "kind": "attack",
        "power": 4,
        "hit": 50,
        "evasion": 0,
        "crit_gain": 25,
        "field_power": 6,
        "field_hit": 0,
        "life": 2,
        "place_cost": 8,
        "match_cost": 12,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "heavy",
        "light",
        "precise",
        "echoing",
        "dull",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "content_card_id": "SCN-001-CRD02",
      "source_target_ids": [
        "SCN-001-ACT02"
      ],
      "source": "PT-NT scenario.cards/newCard/cost and card_overrides",
      "affix_source": "existing AO1 kind/family constraints; no new affix",
      "information_signature": "{\"type\":\"nt_pressure\",\"name\":\"潮底の踏み足\",\"attr\":\"B\",\"kind\":\"attack\",\"power\":4,\"hit\":50,\"evasion\":0,\"crit_gain\":25,\"field_power\":6,\"field_hit\":0,\"life\":2,\"place_cost\":8,\"match_cost\":12,\"consume_on_recover\":null}"
    },
    "nt_stop": {
      "base_id": "nt_stop",
      "registry_id": "CW-M1-cards-0.1",
      "card": {
        "type": "nt_stop",
        "name": "汐留め",
        "attr": "D",
        "kind": "guard",
        "power": 3,
        "hit": 0,
        "evasion": 20,
        "crit_gain": 20,
        "field_power": 2,
        "field_hit": 20,
        "life": 2,
        "place_cost": 10,
        "match_cost": 10,
        "consume_on_recover": null
      },
      "affix_allowlist": [
        "light",
        "sturdy",
        "frail"
      ],
      "free_initial": false,
      "offer_requires_kept_unlock": true,
      "content_card_id": "SCN-001-CRD03",
      "source_target_ids": [
        "SCN-001-ACT03",
        "SCN-001-ACT05"
      ],
      "source": "PT-NT scenario.cards/newCard/cost and card_overrides",
      "affix_source": "existing AO1 kind/family constraints; no new affix",
      "information_signature": "{\"type\":\"nt_stop\",\"name\":\"汐留め\",\"attr\":\"D\",\"kind\":\"guard\",\"power\":3,\"hit\":0,\"evasion\":20,\"crit_gain\":20,\"field_power\":2,\"field_hit\":20,\"life\":2,\"place_cost\":10,\"match_cost\":10,\"consume_on_recover\":null}"
    }
  },
  "runtime_supply_cards": {
    "weak_A": {
      "type": "weak_A",
      "name": "弱攻撃札",
      "attr": "A",
      "kind": "attack",
      "power": 2,
      "hit": 20,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 2,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "filler_A": {
      "type": "filler_A",
      "name": "補填専用札",
      "attr": "A",
      "kind": "none",
      "power": 0,
      "hit": 0,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 1,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "weak_B": {
      "type": "weak_B",
      "name": "弱攻撃札",
      "attr": "B",
      "kind": "attack",
      "power": 2,
      "hit": 20,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 2,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "filler_B": {
      "type": "filler_B",
      "name": "補填専用札",
      "attr": "B",
      "kind": "none",
      "power": 0,
      "hit": 0,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 1,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "weak_C": {
      "type": "weak_C",
      "name": "弱攻撃札",
      "attr": "C",
      "kind": "attack",
      "power": 2,
      "hit": 20,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 2,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "filler_C": {
      "type": "filler_C",
      "name": "補填専用札",
      "attr": "C",
      "kind": "none",
      "power": 0,
      "hit": 0,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 1,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "weak_D": {
      "type": "weak_D",
      "name": "弱攻撃札",
      "attr": "D",
      "kind": "attack",
      "power": 2,
      "hit": 20,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 2,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    },
    "filler_D": {
      "type": "filler_D",
      "name": "補填専用札",
      "attr": "D",
      "kind": "none",
      "power": 0,
      "hit": 0,
      "evasion": 0,
      "crit_gain": 25,
      "field_power": 0,
      "field_hit": 0,
      "life": 1,
      "place_cost": 10,
      "match_cost": 10,
      "consume_on_recover": null
    }
  },
  "targets": {
    "SCN-001-ACT01": {
      "id": "SCN-001-ACT01",
      "runtime_actor_id": "V0",
      "knowledge_profile_id": "SCN-001/target/ACT01",
      "catalogue_version": "CW-M1-cards-0.1/ACT01/initial-1",
      "display_name": "逆流する地下水路",
      "action_label": "進む",
      "remaining_label": "道のり",
      "purpose": "passage",
      "spec": {
        "hp": 40,
        "hand_size": 1,
        "purpose": "passage",
        "targets": [
          "P"
        ],
        "max_posture": 1,
        "action_cost_scale": 1
      },
      "initial_card_counts": {
        "weak_B": 6,
        "weak_C": 2,
        "weak_D": 2,
        "nt_flow": 2
      },
      "initial_replacements": [
        {
          "base": "weak_A",
          "count": 2,
          "replacement": "nt_flow"
        }
      ],
      "reward_id": "SCN-001-RW01",
      "target_selection": "P only while active",
      "npc_policy_reference": "AH.Game.targets and inherited AM public automatic selection; same source roles, no future-information policy",
      "source_cards": "nt_flow",
      "same_type_across_runs": true
    },
    "SCN-001-ACT02": {
      "id": "SCN-001-ACT02",
      "runtime_actor_id": "E1",
      "knowledge_profile_id": "SCN-001/target/ACT02",
      "catalogue_version": "CW-M1-cards-0.1/ACT02/initial-1",
      "display_name": "漂着した潜水服",
      "action_label": "攻撃",
      "remaining_label": "余力",
      "purpose": "optional_enemy",
      "spec": {
        "hp": 24,
        "hand_size": 3,
        "purpose": "optional_enemy",
        "targets": [
          "P"
        ],
        "max_posture": 100,
        "action_cost_scale": 1
      },
      "initial_card_counts": {
        "f": 2,
        "h": 2,
        "j": 2,
        "g": 2,
        "r": 2,
        "nt_pressure": 2
      },
      "initial_replacements": [
        {
          "base": "l",
          "count": 2,
          "replacement": "nt_pressure"
        }
      ],
      "reward_id": "SCN-001-RW02",
      "target_selection": "P only while active",
      "npc_policy_reference": "AH.Game.targets and inherited AM public automatic selection; same source roles, no future-information policy",
      "source_cards": "nt_pressure",
      "same_type_across_runs": true
    },
    "SCN-001-ACT03": {
      "id": "SCN-001-ACT03",
      "runtime_actor_id": "V1",
      "knowledge_profile_id": "SCN-001/target/ACT03",
      "catalogue_version": "CW-M1-cards-0.1/ACT03/initial-1",
      "display_name": "奥の水門",
      "action_label": "調える",
      "remaining_label": "復旧残量",
      "purpose": "terminal",
      "spec": {
        "hp": 20,
        "hand_size": 1,
        "purpose": "terminal",
        "targets": [
          "P"
        ],
        "max_posture": 100,
        "action_cost_scale": 1
      },
      "initial_card_counts": {
        "weak_A": 2,
        "weak_B": 6,
        "weak_C": 2,
        "nt_stop": 2
      },
      "initial_replacements": [
        {
          "base": "weak_D",
          "count": 2,
          "replacement": "nt_stop"
        }
      ],
      "reward_id": "SCN-001-RW03",
      "target_selection": "P only while active",
      "npc_policy_reference": "AH.Game.targets and inherited AM public automatic selection; same source roles, no future-information policy",
      "source_cards": "nt_stop",
      "same_type_across_runs": true
    },
    "SCN-001-ACT04": {
      "id": "SCN-001-ACT04",
      "runtime_actor_id": "V0",
      "knowledge_profile_id": "SCN-001/target/ACT04",
      "catalogue_version": "CW-M1-cards-0.1/ACT04/initial-1",
      "display_name": "潮の残る地下水路",
      "action_label": "進む",
      "remaining_label": "道のり",
      "purpose": "passage",
      "spec": {
        "hp": 40,
        "hand_size": 1,
        "purpose": "passage",
        "targets": [
          "P"
        ],
        "max_posture": 1,
        "action_cost_scale": 1
      },
      "initial_card_counts": {
        "weak_B": 6,
        "weak_C": 2,
        "weak_D": 2,
        "nt_flow": 2
      },
      "initial_replacements": [
        {
          "base": "weak_A",
          "count": 2,
          "replacement": "nt_flow"
        }
      ],
      "reward_id": "SCN-001-RW04",
      "target_selection": "P only while active",
      "npc_policy_reference": "AH.Game.targets and inherited AM public automatic selection; same source roles, no future-information policy",
      "source_cards": "nt_flow",
      "same_type_across_runs": true
    },
    "SCN-001-ACT05": {
      "id": "SCN-001-ACT05",
      "runtime_actor_id": "V1",
      "knowledge_profile_id": "SCN-001/target/ACT05",
      "catalogue_version": "CW-M1-cards-0.1/ACT05/initial-1",
      "display_name": "管理用連絡路",
      "action_label": "辿る",
      "remaining_label": "道のり",
      "purpose": "terminal",
      "spec": {
        "hp": 20,
        "hand_size": 1,
        "purpose": "terminal",
        "targets": [
          "P"
        ],
        "max_posture": 100,
        "action_cost_scale": 1
      },
      "initial_card_counts": {
        "weak_A": 2,
        "weak_B": 6,
        "weak_C": 2,
        "nt_stop": 2
      },
      "initial_replacements": [
        {
          "base": "weak_D",
          "count": 2,
          "replacement": "nt_stop"
        }
      ],
      "reward_id": "SCN-001-RW05",
      "target_selection": "P only while active",
      "npc_policy_reference": "AH.Game.targets and inherited AM public automatic selection; same source roles, no future-information policy",
      "source_cards": "nt_stop",
      "same_type_across_runs": true
    }
  },
  "target_sets": {
    "SCN-001-SET-UNRESOLVED": {
      "targets": [
        "SCN-001-ACT01",
        "SCN-001-ACT02",
        "SCN-001-ACT03"
      ],
      "initial_targets": [
        "SCN-001-ACT01",
        "SCN-001-ACT02"
      ],
      "later_target": "SCN-001-ACT03",
      "route": "A",
      "slot_map": {
        "V0": "SCN-001-ACT01",
        "E1": "SCN-001-ACT02",
        "V1": "SCN-001-ACT03"
      },
      "fresh_departure": "full entry stats and empty run reward ledger; no previous run damage/protection/cards",
      "resume": "restore exact existing actors including retirements; no new enter"
    },
    "SCN-001-SET-REVISIT": {
      "targets": [
        "SCN-001-ACT04",
        "SCN-001-ACT02",
        "SCN-001-ACT05"
      ],
      "initial_targets": [
        "SCN-001-ACT04",
        "SCN-001-ACT02"
      ],
      "later_target": "SCN-001-ACT05",
      "route": "A",
      "slot_map": {
        "V0": "SCN-001-ACT04",
        "E1": "SCN-001-ACT02",
        "V1": "SCN-001-ACT05"
      },
      "fresh_departure": "full entry stats and empty run reward ledger; no previous run damage/protection/cards",
      "resume": "restore exact existing actors including retirements; no new enter"
    }
  },
  "transitions": {
    "SCN-001-ACT01-TRAVERSED": {
      "event_id": "SCN-001-ACT01-TRAVERSED",
      "trigger": {
        "kind": "resolution",
        "actor": "V0",
        "result": "traversed",
        "target_id": "SCN-001-ACT01"
      },
      "reward_id": "SCN-001-RW01",
      "protect": true,
      "retire_surviving_targets": [
        "SCN-001-ACT02"
      ],
      "enter_targets": [
        "SCN-001-ACT03"
      ],
      "pause_scene_id": "SCN-001-S03",
      "terminal": false,
      "case_resolution": false,
      "priority": "use confirmed engine outcome; defeat suppresses clear text and case resolution; retired never emits defeated reward"
    },
    "SCN-001-ACT02-DEFEATED": {
      "event_id": "SCN-001-ACT02-DEFEATED",
      "trigger": {
        "kind": "resolution",
        "actor": "E1",
        "result": "defeated",
        "target_id": "SCN-001-ACT02"
      },
      "reward_id": "SCN-001-RW02",
      "protect": false,
      "retire_surviving_targets": [],
      "enter_targets": [],
      "pause_scene_id": null,
      "terminal": false,
      "case_resolution": false,
      "priority": "use confirmed engine outcome; defeat suppresses clear text and case resolution; retired never emits defeated reward"
    },
    "SCN-001-ACT03-TRAVERSED": {
      "event_id": "SCN-001-ACT03-TRAVERSED",
      "trigger": {
        "kind": "resolution",
        "actor": "V1",
        "result": "traversed",
        "target_id": "SCN-001-ACT03"
      },
      "reward_id": "SCN-001-RW03",
      "protect": false,
      "retire_surviving_targets": [],
      "enter_targets": [],
      "pause_scene_id": "SCN-001-S05",
      "terminal": true,
      "case_resolution": true,
      "priority": "use confirmed engine outcome; defeat suppresses clear text and case resolution; retired never emits defeated reward"
    },
    "SCN-001-ACT04-TRAVERSED": {
      "event_id": "SCN-001-ACT04-TRAVERSED",
      "trigger": {
        "kind": "resolution",
        "actor": "V0",
        "result": "traversed",
        "target_id": "SCN-001-ACT04"
      },
      "reward_id": "SCN-001-RW04",
      "protect": true,
      "retire_surviving_targets": [
        "SCN-001-ACT02"
      ],
      "enter_targets": [
        "SCN-001-ACT05"
      ],
      "pause_scene_id": "SCN-001-S03R",
      "terminal": false,
      "case_resolution": false,
      "priority": "use confirmed engine outcome; defeat suppresses clear text and case resolution; retired never emits defeated reward"
    },
    "SCN-001-ACT05-TRAVERSED": {
      "event_id": "SCN-001-ACT05-TRAVERSED",
      "trigger": {
        "kind": "resolution",
        "actor": "V1",
        "result": "traversed",
        "target_id": "SCN-001-ACT05"
      },
      "reward_id": "SCN-001-RW05",
      "protect": false,
      "retire_surviving_targets": [],
      "enter_targets": [],
      "pause_scene_id": "SCN-001-S05R",
      "terminal": true,
      "case_resolution": false,
      "priority": "use confirmed engine outcome; defeat suppresses clear text and case resolution; retired never emits defeated reward"
    }
  },
  "rewards": {
    "SCN-001-RW01": {
      "id": "SCN-001-RW01",
      "target_id": "SCN-001-ACT01",
      "source_event_id": "SCN-001-ACT01-TRAVERSED",
      "legacy_engine_key": "A/V0",
      "ledger_key": "JSON.stringify(['CW-M1-reward-1',run,reward_id,source_event_id])",
      "once_scope": "run + reward_id + source_event_id",
      "source_fields": [
        "run",
        "case_id",
        "mode",
        "target_set_id",
        "target_id",
        "catalogue_version",
        "content_set_id",
        "source_event_id",
        "legacy_engine_key"
      ],
      "items": [
        {
          "kind": "points",
          "amount_units": 100
        },
        {
          "kind": "material",
          "type": "M",
          "amount": 1
        },
        {
          "kind": "unlock",
          "type": "nt_flow"
        }
      ],
      "offer_tier": "I",
      "protect_all_acquired_after_award": true,
      "grants_individual": false,
      "repeat_unlock": "set union only; no duplicate payment or item",
      "achievement_reward": false
    },
    "SCN-001-RW02": {
      "id": "SCN-001-RW02",
      "target_id": "SCN-001-ACT02",
      "source_event_id": "SCN-001-ACT02-DEFEATED",
      "legacy_engine_key": "A/E1",
      "ledger_key": "JSON.stringify(['CW-M1-reward-1',run,reward_id,source_event_id])",
      "once_scope": "run + reward_id + source_event_id",
      "source_fields": [
        "run",
        "case_id",
        "mode",
        "target_set_id",
        "target_id",
        "catalogue_version",
        "content_set_id",
        "source_event_id",
        "legacy_engine_key"
      ],
      "items": [
        {
          "kind": "points",
          "amount_units": 100
        },
        {
          "kind": "unlock",
          "type": "nt_pressure"
        }
      ],
      "offer_tier": "I",
      "protect_all_acquired_after_award": false,
      "grants_individual": false,
      "repeat_unlock": "set union only; no duplicate payment or item",
      "achievement_reward": false
    },
    "SCN-001-RW03": {
      "id": "SCN-001-RW03",
      "target_id": "SCN-001-ACT03",
      "source_event_id": "SCN-001-ACT03-TRAVERSED",
      "legacy_engine_key": "A/V1",
      "ledger_key": "JSON.stringify(['CW-M1-reward-1',run,reward_id,source_event_id])",
      "once_scope": "run + reward_id + source_event_id",
      "source_fields": [
        "run",
        "case_id",
        "mode",
        "target_set_id",
        "target_id",
        "catalogue_version",
        "content_set_id",
        "source_event_id",
        "legacy_engine_key"
      ],
      "items": [
        {
          "kind": "points",
          "amount_units": 200
        },
        {
          "kind": "unlock",
          "type": "nt_stop"
        }
      ],
      "offer_tier": "I",
      "protect_all_acquired_after_award": false,
      "grants_individual": false,
      "repeat_unlock": "set union only; no duplicate payment or item",
      "achievement_reward": false
    },
    "SCN-001-RW04": {
      "id": "SCN-001-RW04",
      "target_id": "SCN-001-ACT04",
      "source_event_id": "SCN-001-ACT04-TRAVERSED",
      "legacy_engine_key": "A/V0",
      "ledger_key": "JSON.stringify(['CW-M1-reward-1',run,reward_id,source_event_id])",
      "once_scope": "run + reward_id + source_event_id",
      "source_fields": [
        "run",
        "case_id",
        "mode",
        "target_set_id",
        "target_id",
        "catalogue_version",
        "content_set_id",
        "source_event_id",
        "legacy_engine_key"
      ],
      "items": [
        {
          "kind": "points",
          "amount_units": 100
        },
        {
          "kind": "material",
          "type": "M",
          "amount": 1
        },
        {
          "kind": "unlock",
          "type": "nt_flow"
        }
      ],
      "offer_tier": "I",
      "protect_all_acquired_after_award": true,
      "grants_individual": false,
      "repeat_unlock": "set union only; no duplicate payment or item",
      "achievement_reward": false
    },
    "SCN-001-RW05": {
      "id": "SCN-001-RW05",
      "target_id": "SCN-001-ACT05",
      "source_event_id": "SCN-001-ACT05-TRAVERSED",
      "legacy_engine_key": "A/V1",
      "ledger_key": "JSON.stringify(['CW-M1-reward-1',run,reward_id,source_event_id])",
      "once_scope": "run + reward_id + source_event_id",
      "source_fields": [
        "run",
        "case_id",
        "mode",
        "target_set_id",
        "target_id",
        "catalogue_version",
        "content_set_id",
        "source_event_id",
        "legacy_engine_key"
      ],
      "items": [
        {
          "kind": "points",
          "amount_units": 200
        },
        {
          "kind": "unlock",
          "type": "nt_stop"
        }
      ],
      "offer_tier": "I",
      "protect_all_acquired_after_award": false,
      "grants_individual": false,
      "repeat_unlock": "set union only; no duplicate payment or item",
      "achievement_reward": false
    }
  },
  "modes": {
    "SCN-001-MODE-FIRST": {
      "value": "first",
      "target_set_id": "SCN-001-SET-UNRESOLVED",
      "entry_scene_id": "SCN-001-S02",
      "request_scene_id": "SCN-001-S01",
      "select_when": {
        "all": [
          {
            "eq": [
              "case.status",
              "unresolved"
            ]
          },
          {
            "eq": [
              "has_departure",
              false
            ]
          }
        ]
      },
      "selection_gate": "only home successful new depart, after saved-active/return precedence",
      "persist_at": "session.active.mode",
      "resume_selection": false
    },
    "SCN-001-MODE-RETRY": {
      "value": "retry",
      "target_set_id": "SCN-001-SET-UNRESOLVED",
      "entry_scene_id": "SCN-001-S02",
      "request_scene_id": "SCN-001-S01",
      "select_when": {
        "all": [
          {
            "eq": [
              "case.status",
              "unresolved"
            ]
          },
          {
            "eq": [
              "has_departure",
              true
            ]
          }
        ]
      },
      "selection_gate": "only home successful new depart, after saved-active/return precedence",
      "persist_at": "session.active.mode",
      "resume_selection": false
    },
    "SCN-001-MODE-REVISIT": {
      "value": "revisit",
      "target_set_id": "SCN-001-SET-REVISIT",
      "entry_scene_id": "SCN-001-S02R",
      "request_scene_id": "SCN-001-S01R",
      "select_when": {
        "eq": [
          "case.status",
          "resolved"
        ]
      },
      "selection_gate": "only home successful new depart, after saved-active/return precedence",
      "persist_at": "session.active.mode",
      "resume_selection": false
    }
  },
  "scenes": {
    "SCN-001-S01": {
      "id": "SCN-001-S01",
      "next_scene_id": "SCN-001-S02",
      "pause": false,
      "kind": "request",
      "progress_rule": "explicit depart"
    },
    "SCN-001-S01R": {
      "id": "SCN-001-S01R",
      "next_scene_id": "SCN-001-S02R",
      "pause": false,
      "kind": "request",
      "progress_rule": "explicit depart"
    },
    "SCN-001-S02": {
      "id": "SCN-001-S02",
      "next_scene_id": null,
      "pause": true,
      "kind": "entry",
      "progress_rule": "continue_scene releases pause and advances only to next stop/player ready/outcome"
    },
    "SCN-001-S02R": {
      "id": "SCN-001-S02R",
      "next_scene_id": null,
      "pause": true,
      "kind": "entry",
      "progress_rule": "continue_scene releases pause and advances only to next stop/player ready/outcome"
    },
    "SCN-001-S02a": {
      "id": "SCN-001-S02a",
      "next_scene_id": null,
      "pause": false,
      "kind": "optional_enemy_event",
      "progress_rule": "display only"
    },
    "SCN-001-S03": {
      "id": "SCN-001-S03",
      "next_scene_id": "SCN-001-S04",
      "pause": true,
      "kind": "port",
      "progress_rule": "continue_scene to next text with unchanged game time/HP/cards"
    },
    "SCN-001-S03R": {
      "id": "SCN-001-S03R",
      "next_scene_id": "SCN-001-S04R",
      "pause": true,
      "kind": "port",
      "progress_rule": "continue_scene to next text with unchanged game time/HP/cards"
    },
    "SCN-001-S04": {
      "id": "SCN-001-S04",
      "next_scene_id": null,
      "pause": true,
      "kind": "gate",
      "progress_rule": "continue_scene releases pause and advances only to next stop/player ready/outcome"
    },
    "SCN-001-S04R": {
      "id": "SCN-001-S04R",
      "next_scene_id": null,
      "pause": true,
      "kind": "gate",
      "progress_rule": "continue_scene releases pause and advances only to next stop/player ready/outcome"
    },
    "SCN-001-S05": {
      "id": "SCN-001-S05",
      "next_scene_id": "SCN-001-S06",
      "pause": true,
      "kind": "settled_end",
      "progress_rule": "no game advance; settled receipt already exists"
    },
    "SCN-001-S05R": {
      "id": "SCN-001-S05R",
      "next_scene_id": "SCN-001-S06",
      "pause": true,
      "kind": "settled_end",
      "progress_rule": "no game advance; settled receipt already exists"
    },
    "SCN-001-S06": {
      "id": "SCN-001-S06",
      "next_scene_id": "SCN-001-S07",
      "pause": false,
      "kind": "return",
      "progress_rule": "explicit ack_return"
    },
    "SCN-001-S07": {
      "id": "SCN-001-S07",
      "next_scene_id": null,
      "pause": false,
      "kind": "home",
      "progress_rule": "display only"
    }
  },
  "texts": {
    "SCN-001-TXT01": {
      "source_id": "TXT01",
      "short_text": "「雨は降っていないんです。それなのに夜になると、地下から潮の匂いがして。品物は上へ移しましたが、いつまでも使わないわけにはいかなくて」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "first"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S01"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT02": {
      "source_id": "TXT02",
      "short_text": "流れに逆らい、障害を越えて奥へ進む探索。途中の相手を調べる余地もある。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S01"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT03": {
      "source_id": "TXT03",
      "short_text": "水が、下り坂を上ってくる。壁の白い筋を辿ると、照明の途切れた奥へ続いていた。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "first"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT04": {
      "source_id": "TXT04",
      "short_text": "古い潜水服が流れの中に立っている。足元の水だけが割れ、こちらへ重い腕を伸ばした。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02",
                "SCN-001-S02R"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "known_actor.ACT02",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT05": {
      "source_id": "TXT05",
      "short_text": "通路を抜けると、頭上に海があった。遠い舟底の影が、港の屋根をゆっくり横切っていく。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S03"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL02",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT06": {
      "source_id": "TXT06",
      "short_text": "港の壁にも、地下で見た水位の筋がある。奥の水門で噴き返した白い水が、こちらの通路へ流れ込んでいた。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S03"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL02",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT07": {
      "source_id": "TXT07",
      "short_text": "鎖が歯車に噛み込み、逃がし口を開いたまま留めている。擦れた正常位置は、そのすぐ隣にあった。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S04"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL03",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT08": {
      "source_id": "TXT08",
      "short_text": "噛み込んだ鎖が外れ、水門がゆっくり戻る。足元へ向かっていた水が曲がり、港の水路へ流れていった。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S05"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT09": {
      "source_id": "TXT09",
      "short_text": "「地下の水、引きました。まずは空の棚から戻してみます。……奥には、港があったんですか」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT10": {
      "source_id": "TXT10",
      "short_text": "地図に描き足した港は、まだ小さな点だ。その脇に、見覚えのない渡り場の名が残った。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S07"
              ]
            ]
          },
          {
            "eq": [
              "clues.CL05",
              true
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT11": {
      "source_id": "TXT11",
      "short_text": "水門は今日も、二つの流れを分けている。荷揚げの声を背に、今度は古い連絡路の印を辿る。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S03R"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-DETAIL01": {
      "source_id": "DETAIL01",
      "short_text": "塩を含んだ水は、乾いても白く残る。床には何度も拭いた跡があり、低い棚だけが空になっている。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "in": [
          "scene_id",
          [
            "SCN-001-S01",
            "SCN-001-S02"
          ]
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-DETAIL02": {
      "source_id": "DETAIL02",
      "short_text": "窓の内側は暗く、中に何があるのかは分からない。潮が引いても、重い靴だけは床から離れない。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02",
                "SCN-001-S02R"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "catalogue.ACT02",
                true
              ]
            }
          }
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-DETAIL03": {
      "source_id": "DETAIL03",
      "short_text": "「上の潮が満ちると、ここも上がる。それはいつものことだよ。おかしいのは、引く方の水まで、あの古い口へ吸われることだ」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "in": [
          "scene_id",
          [
            "SCN-001-S03"
          ]
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-DETAIL04": {
      "source_id": "DETAIL04",
      "short_text": "長く使われた工具と、乾かしかけの手袋が並ぶ。錆びた遺構の一部も、ここではまだ毎日の仕事場らしい。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "in": [
          "scene_id",
          [
            "SCN-001-S03",
            "SCN-001-S03R"
          ]
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-DETAIL05": {
      "source_id": "DETAIL05",
      "short_text": "正常な位置だけが磨かれている。壊して取り払うより、ずれた鎖を戻せば流れを切り替えられそうだ。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S04",
                "SCN-001-S05"
              ]
            ]
          }
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-DETAIL06": {
      "source_id": "DETAIL06",
      "short_text": "水門の裏に古い案内板がある。港の名の隣に「渡り場」の文字。使われなくなっても、道筋は残っているらしい。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "in": [
          "scene_id",
          [
            "SCN-001-S04",
            "SCN-001-S05",
            "SCN-001-S04R",
            "SCN-001-S05R"
          ]
        ]
      },
      "kind": "detail",
      "economic_effect": null
    },
    "SCN-001-COND01": {
      "source_id": "COND01",
      "short_text": "逆らう水の働きが、掌ほどの櫂に収まる。今なら、この流れを使えそうだ。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "current.borrowed_first.nt_flow",
          true
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND02": {
      "source_id": "COND02",
      "short_text": "靴底を重ねると、足元が沈むように落ち着く。あの潜水服が立っていた理由の一端が分かった。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "current.borrowed_first.nt_pressure",
          true
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND03": {
      "source_id": "COND03",
      "short_text": "潜水服の腕が下がる。重い靴はそこに残り、水だけが脇を抜けていった。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "current.enemy_result",
          "defeated"
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND04": {
      "source_id": "COND04",
      "short_text": "通路の角を越える。振り返ると、潜水服はまだ、同じ流れの中に立っていた。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "current.enemy_result",
          "retired"
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND05": {
      "source_id": "COND05",
      "short_text": "「水の来る側に、別の港がありました。奥はまだ調べ切れていません」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "withdrawal"
            ]
          },
          {
            "eq": [
              "current.t1",
              true
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL03",
                true
              ]
            }
          }
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND06": {
      "source_id": "COND06",
      "short_text": "「奥の水門が戻らなくなっています。原因は分かりましたが、まだ直せていません」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "withdrawal"
            ]
          },
          {
            "eq": [
              "current.t1",
              true
            ]
          },
          {
            "eq": [
              "clues.CL03",
              true
            ]
          }
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-COND07": {
      "source_id": "COND07",
      "short_text": "「流れは奥から来ています。今回は、そこまでを確かめて戻りました」",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "withdrawal"
            ]
          },
          {
            "not": {
              "eq": [
                "current.t1",
                true
              ]
            }
          },
          {
            "eq": [
              "clues.CL01",
              true
            ]
          }
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-TXT10B": {
      "source_id": "TXT10B",
      "short_text": "地図に描き足した港は、まだ小さな点だ。調べていない場所は、その外へ広がっている。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S07"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL05",
                true
              ]
            }
          },
          {
            "eq": [
              "clues.CL02",
              true
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT10C": {
      "source_id": "TXT10C",
      "short_text": "地図の線は、確かめたところで途切れている。次は何を持って、どこまで進もうか。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S07"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL02",
                true
              ]
            }
          },
          {
            "not": {
              "eq": [
                "clues.CL05",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT12": {
      "source_id": "TXT12",
      "short_text": "地下への流入は、まだ止まっていない。前に確かめたことを手掛かりに、もう一度、流れの先へ向かう。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "retry"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S01"
              ]
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL03",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT13": {
      "source_id": "TXT13",
      "short_text": "原因は、奥の水門に噛み込んだ鎖だ。前の調査をもとに手段を整え、今度は流れを戻しに行く。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "retry"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S01"
              ]
            ]
          },
          {
            "eq": [
              "clues.CL03",
              true
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT14": {
      "source_id": "TXT14",
      "short_text": "入口の水は、まだ奥から押し寄せている。前に通った道を確かめながら、足元と今の流れを見直す。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "retry"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT15": {
      "source_id": "TXT15",
      "short_text": "水路を抜け、頭上の海の下へ出る。港の水位の筋を辿ると、奥の水門から続く白い流れが見える。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S03"
              ]
            ]
          },
          {
            "eq": [
              "clues.CL02",
              true
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT16": {
      "source_id": "TXT16",
      "short_text": "噛み込んだ鎖は、まだ同じ位置にある。磨かれた正常位置を確かめ、残る余力で作業を進められるか考える。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S04"
              ]
            ]
          },
          {
            "eq": [
              "clues.CL03",
              true
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT17": {
      "source_id": "TXT17",
      "short_text": "水門のある港から、管理用の連絡路を調べに行く。今度の仕事は、道のつながりを確かめることだ。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S01R"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT18": {
      "source_id": "TXT18",
      "short_text": "水路の床を、港の潮が薄く洗っている。日常へ押し寄せていた流れは止まり、通路の先から荷揚げの音が届く。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02R"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT19": {
      "source_id": "TXT19",
      "short_text": "正常に動く水門の脇から、古い通行標が続いている。潮風に削られた印と足場を確かめ、連絡路を辿る。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S04R"
              ]
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT20": {
      "source_id": "TXT20",
      "short_text": "途切れかけた通行標が、先の印へつながった。振り返ると、歩いてきた連絡路と港の明かりが一つの道に見える。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S05R"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT21": {
      "source_id": "TXT21",
      "short_text": "地図に、港から続く道筋を描き足す。水門を直した日の記録の隣に、今日確かめたことが増えた。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT22": {
      "source_id": "TXT22",
      "short_text": "余力が尽き、緊急脱出して戻った。確かめたことと、持ち帰れなかった成果を振り返る。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "defeat"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT23": {
      "source_id": "TXT23",
      "short_text": "今回は調査を途中で切り上げた。水門を直した仕事は、前回の記録に残っている。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "withdrawal"
            ]
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT24": {
      "source_id": "TXT24",
      "short_text": "今回は奥へ進まず、戻った。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S06"
              ]
            ]
          },
          {
            "eq": [
              "outcome",
              "withdrawal"
            ]
          },
          {
            "not": {
              "eq": [
                "current.t1",
                true
              ]
            }
          },
          {
            "not": {
              "eq": [
                "clues.CL01",
                true
              ]
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-TXT25": {
      "source_id": "TXT25",
      "short_text": "見覚えのある型の潜水服が、流れの中に立っている。足元を確かめながら、重い腕の届く範囲を測る。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "in": [
              "scene_id",
              [
                "SCN-001-S02",
                "SCN-001-S02R"
              ]
            ]
          },
          {
            "not": {
              "not": {
                "eq": [
                  "known_actor.ACT02",
                  true
                ]
              }
            }
          }
        ]
      },
      "kind": "main",
      "economic_effect": null
    },
    "SCN-001-COND08": {
      "source_id": "COND08",
      "short_text": "圧を受け止める働きが、小さな留め具の形になる。どこへ力を逃がすか、手元で確かめられそうだ。",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "current.borrowed_first.nt_stop",
          true
        ]
      },
      "kind": "conditional",
      "economic_effect": null
    },
    "SCN-001-OBJ-ENTRY": {
      "source_id": "OBJ-ENTRY",
      "short_text": "地下へ流れ込む水の出所を調べる",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL02",
                true
              ]
            }
          },
          {
            "not": {
              "eq": [
                "clues.CL03",
                true
              ]
            }
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-OBJ-PORT": {
      "source_id": "OBJ-PORT",
      "short_text": "奥の水門を確かめる",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "eq": [
              "clues.CL02",
              true
            ]
          },
          {
            "not": {
              "eq": [
                "clues.CL03",
                true
              ]
            }
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-OBJ-REPAIR": {
      "source_id": "OBJ-REPAIR",
      "short_text": "水門を戻し、流入を止める",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "eq": [
              "clues.CL03",
              true
            ]
          },
          {
            "not": {
              "eq": [
                "outcome",
                "clear"
              ]
            }
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-OBJ-REVISIT": {
      "source_id": "OBJ-REVISIT",
      "short_text": "管理用連絡路のつながりを確かめる",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "not": {
              "eq": [
                "outcome",
                "clear"
              ]
            }
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-OBJ-DONE": {
      "source_id": "OBJ-DONE",
      "short_text": "日常側への流入が止まった",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "any": [
              {
                "eq": [
                  "mode",
                  "first"
                ]
              },
              {
                "eq": [
                  "mode",
                  "retry"
                ]
              }
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-OBJ-CHECKED": {
      "source_id": "OBJ-CHECKED",
      "short_text": "連絡路の道筋を確かめた",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "all": [
          {
            "eq": [
              "mode",
              "revisit"
            ]
          },
          {
            "eq": [
              "outcome",
              "clear"
            ]
          }
        ]
      },
      "kind": "objective",
      "economic_effect": null
    },
    "SCN-001-LABEL-RESUME": {
      "source_id": "LABEL-RESUME",
      "short_text": "探索を再開",
      "source_document": "S01-text",
      "source_version": "0.2",
      "eligible_when": {
        "eq": [
          "resuming_unsettled",
          true
        ]
      },
      "kind": "label",
      "economic_effect": null
    }
  },
  "clues": {
    "SCN-001-CL01": {
      "id": "SCN-001-CL01",
      "publication_text_ids": [
        "SCN-001-TXT01",
        "SCN-001-TXT03",
        "SCN-001-TXT14"
      ],
      "trigger": "request/entry actually published",
      "retain_all_outcomes": true,
      "first_event_preserved": true,
      "is_read_flag": false
    },
    "SCN-001-CL02": {
      "id": "SCN-001-CL02",
      "publication_text_ids": [
        "SCN-001-TXT05",
        "SCN-001-TXT06",
        "SCN-001-TXT15"
      ],
      "trigger": "port actually published",
      "retain_all_outcomes": true,
      "first_event_preserved": true,
      "is_read_flag": false
    },
    "SCN-001-CL03": {
      "id": "SCN-001-CL03",
      "publication_text_ids": [
        "SCN-001-TXT07",
        "SCN-001-TXT16"
      ],
      "trigger": "cause actually published",
      "retain_all_outcomes": true,
      "first_event_preserved": true,
      "is_read_flag": false
    },
    "SCN-001-CL04": {
      "id": "SCN-001-CL04",
      "publication_text_ids": [
        "SCN-001-TXT08"
      ],
      "trigger": "valid unresolved clear transaction",
      "retain_all_outcomes": true,
      "first_event_preserved": true,
      "is_read_flag": false
    },
    "SCN-001-CL05": {
      "id": "SCN-001-CL05",
      "publication_text_ids": [
        "SCN-001-DETAIL06"
      ],
      "trigger": "explicit optional detail publication; not availability or TXT17",
      "retain_all_outcomes": true,
      "first_event_preserved": true,
      "is_read_flag": false
    }
  },
  "achievements": {
    "SCN-001-ACH-RESOLVED": {
      "id": "SCN-001-ACH-RESOLVED",
      "once_scope": "case",
      "trigger": "first unresolved RW03 valid clear",
      "reward_items": [],
      "ledger_key": "JSON.stringify(['CW-M1-achievement-1',achievement_id,scope_id])",
      "repeat": "retain first provenance; per-run results recorded separately, no bonus"
    },
    "SCN-001-ACH-CATALOGUE": {
      "id": "SCN-001-ACH-CATALOGUE",
      "once_scope": "profile + catalogue_version",
      "trigger": "first traversed/defeated fact",
      "reward_items": [],
      "ledger_key": "JSON.stringify(['CW-M1-achievement-1',achievement_id,scope_id])",
      "repeat": "retain first provenance; per-run results recorded separately, no bonus"
    },
    "SCN-001-ACH-CLUE": {
      "id": "SCN-001-ACH-CLUE",
      "once_scope": "case + clue_id",
      "trigger": "first actual eligible publication",
      "reward_items": [],
      "ledger_key": "JSON.stringify(['CW-M1-achievement-1',achievement_id,scope_id])",
      "repeat": "retain first provenance; per-run results recorded separately, no bonus"
    },
    "SCN-001-ACH-ROUTE-CHECKED": {
      "id": "SCN-001-ACH-ROUTE-CHECKED",
      "once_scope": "case",
      "trigger": "first revisit RW05 valid clear; per-run completion also stored",
      "reward_items": [],
      "ledger_key": "JSON.stringify(['CW-M1-achievement-1',achievement_id,scope_id])",
      "repeat": "retain first provenance; per-run results recorded separately, no bonus"
    },
    "SCN-001-ACH-UNLOCK": {
      "id": "SCN-001-ACH-UNLOCK",
      "once_scope": "base_id",
      "trigger": "kept unlock set difference",
      "reward_items": [],
      "ledger_key": "JSON.stringify(['CW-M1-achievement-1',achievement_id,scope_id])",
      "repeat": "retain first provenance; per-run results recorded separately, no bonus"
    }
  },
  "engine_version": "CW-M1-engine-0.1",
  "source": {
    "path": "docs/仕様案/接続データ/co-01a/m1-input.v0.1.json",
    "sha256": "5e030a86aa67c5029a4e2b54236bd99b459cacc3c69755d4e04f704942d436d6",
    "git_blob": "8487b2288b4e701953887be90949242f4d951a71"
  }
};
function freeze(x) { if (x && typeof x === "object") { Object.values(x).forEach(freeze); Object.freeze(x); } return x; }
export default freeze(data);
