"""Build-time extraction only; the browser never reads historical trial files."""
from pathlib import Path
import hashlib
import json

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/仕様案/接続データ/co-01a/m1-input.v0.1.json'
data = json.loads(SOURCE.read_text())
keys = ['schema', 'version', 'rule_set_id', 'content_set_id', 'card_registry_id',
        'initial', 'rules', 'cards', 'runtime_supply_cards', 'targets', 'target_sets',
        'transitions', 'rewards', 'modes', 'scenes', 'texts', 'clues', 'achievements']
selected = {k: data[k] for k in keys}
selected['rule_set_id'] = 'CW-M1-rules-0.4'
selected['engine_version'] = 'CW-M1-engine-0.4'
selected['source'] = {'path': str(SOURCE.relative_to(ROOT)),
                      'sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                      'git_blob': '8487b2288b4e701953887be90949242f4d951a71',
                      'base_rule_set_id': data['rule_set_id'], 'rule_amendments': ['D55', 'D56', 'D57']}
target = ROOT / 'src/content/m1.mjs'
target.write_text('// Generated by scripts/generate-m1-content.py; input 0.1 trial values.\n'
                  'const data = ' + json.dumps(selected, ensure_ascii=False, indent=2) + ';\n'
                  'function freeze(x) { if (x && typeof x === "object") { Object.values(x).forEach(freeze); Object.freeze(x); } return x; }\n'
                  'export default freeze(data);\n')
