"""Build-time extraction only; the browser never reads historical trial files."""
from pathlib import Path
import hashlib
import json
import copy

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'docs/仕様案/接続データ/co-01a/m1-input.v0.1.json'
data = json.loads(SOURCE.read_text())
keys = ['schema', 'version', 'rule_set_id', 'content_set_id', 'card_registry_id',
        'initial', 'rules', 'cards', 'runtime_supply_cards', 'targets', 'target_sets',
        'transitions', 'rewards', 'modes', 'scenes', 'texts', 'clues', 'achievements']
selected = {k: data[k] for k in keys}
PATCH = ROOT / 'docs/仕様案/接続データ/co-01a/defense-content.v0.2.json'
patch = json.loads(PATCH.read_text())
selected['previous_content'] = {
    'content_set_id': data['content_set_id'], 'card_registry_id': data['card_registry_id'],
    'version': data['version'], 'card_types': list(data['cards']),
    'targets': copy.deepcopy(data['targets']),
}
# Only an additive card and explicit initial placements may change. Old card values,
# rewards/texts/player preparation are shared with the preserved 0.1 content registry.
card = patch['card']
assert card['type'] not in selected['cards']
selected['cards'][card['type']] = {
    'card': card, 'source': str(PATCH.relative_to(ROOT)),
    'status': 'trial_environment_card', 'player_free': False,
}
for row in patch['placement']:
    target = selected['targets'][row['target_id']]
    assert target['initial_card_counts'][row['base']] >= row['count']
    target['initial_card_counts'][row['base']] -= row['count']
    target['initial_card_counts'][card['type']] = row['count']
    target['initial_replacements'].append({
        'base': row['base'], 'count': row['count'], 'replacement': card['type'],
    })
    target['catalogue_version'] = row['catalogue_version']
selected['version'] = patch['version']
selected['content_set_id'] = patch['content_set_id']
selected['card_registry_id'] = patch['card_registry_id']
selected['rule_set_id'] = 'CW-M1-rules-0.5'
selected['engine_version'] = 'CW-M1-engine-0.5'
selected['source'] = {'path': str(SOURCE.relative_to(ROOT)),
                      'sha256': hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
                      'git_blob': '8487b2288b4e701953887be90949242f4d951a71',
                      'base_rule_set_id': data['rule_set_id'], 'rule_amendments': ['D55', 'D56', 'D57', 'D58'],
                      'content_patch': str(PATCH.relative_to(ROOT)),
                      'content_patch_sha256': hashlib.sha256(PATCH.read_bytes()).hexdigest()}
target = ROOT / 'src/content/m1.mjs'
target.write_text('// Generated by scripts/generate-m1-content.py; base input 0.1 + defense trial content 0.2.\n'
                  'const data = ' + json.dumps(selected, ensure_ascii=False, indent=2) + ';\n'
                  'function freeze(x) { if (x && typeof x === "object") { Object.values(x).forEach(freeze); Object.freeze(x); } return x; }\n'
                  'export default freeze(data);\n')
